package healthfirstpims;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import healthfirstpims.database.DatabaseConnection;

public class CashierPOS extends javax.swing.JFrame {
    private int loggedInUserId;
    private String loggedInUserName;
    private double total = 0.0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CashierPOS.class.getName());

    /**
     * Creates new form CashierPOS
     */
    public CashierPOS() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(0, 102, 102));
        
        setupCartTable();
        loadMedicines();
        
        
    }
    
    public CashierPOS(int userId, String fullName){
        initComponents();
        
        this.loggedInUserId = userId;
        this.loggedInUserName = fullName;
        
        setupCartTable();
        loadMedicines();
        getContentPane().setBackground(new java.awt.Color(0, 102, 102));
    }
    
    private void setupCartTable() {

    DefaultTableModel model = new DefaultTableModel(
        new Object[][]{},
        new String[]{
            "Medicine ID",
            "Medicine",
            "Quantity",
            "Price",
            "Subtotal"
        }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tblCartTwo.setModel(model);
    lblTotal.setText("Total: R0.00");
}
    private void loadMedicines() {

    cmbMedicine.removeAllItems();

    String sql = "SELECT medicine_id, name, price, quantity_in_stock "
               + "FROM medicines "
               + "WHERE quantity_in_stock > 0 "
               + "ORDER BY name";

    try {
        Connection con = DatabaseConnection.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            int id = rs.getInt("medicine_id");
            String name = rs.getString("name");
            double price = rs.getDouble("price");
            int stock = rs.getInt("quantity_in_stock");

            cmbMedicine.addItem(
                id + " - " + name
                + " | R" + String.format("%.2f", price)
                + " | Stock: " + stock
            );
        }

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            this,
            "Error loading medicines: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMedicine = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        cmbMedicine = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartTwo = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnClearCart = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("CASHIER POS");

        lblMedicine.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicine.setText("Medicine:");

        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity");

        cmbMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblCartTwo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Medicine ID", "Medicine", "Quantity", "Price", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblCartTwo);

        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: R0.00");

        btnLogout.setBackground(new java.awt.Color(255, 0, 51));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnClearCart.setText("CLEAR CART");
        btnClearCart.setBorderPainted(false);
        btnClearCart.setContentAreaFilled(false);
        btnClearCart.setFocusPainted(false);
        btnClearCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearCartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearCartMouseExited(evt);
            }
        });
        btnClearCart.addActionListener(this::btnClearCartActionPerformed);

        btnRemoveItem.setText("REMOVE ITEM");
        btnRemoveItem.setBorderPainted(false);
        btnRemoveItem.setContentAreaFilled(false);
        btnRemoveItem.setFocusPainted(false);
        btnRemoveItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoveItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoveItemMouseExited(evt);
            }
        });
        btnRemoveItem.addActionListener(this::btnRemoveItemActionPerformed);

        btnCheckout.setText("CHECKOUT");
        btnCheckout.setBorderPainted(false);
        btnCheckout.setContentAreaFilled(false);
        btnCheckout.setFocusPainted(false);
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
        });
        btnCheckout.addActionListener(this::btnCheckoutActionPerformed);

        btnAdd.setText("ADD TO CART");
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setFocusPainted(false);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(this::btnAddActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRemoveItem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClearCart, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMedicine)
                                    .addComponent(lblQuantity))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicine))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addGap(44, 44, 44)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String selectedMedicine = (String) cmbMedicine.getSelectedItem();
        String quantityText = txtQuantity.getText().trim();

if (selectedMedicine == null) {
    JOptionPane.showMessageDialog(this,
            "Please select a medicine.");
    return;
}

if (quantityText.isEmpty()) {
    JOptionPane.showMessageDialog(this,
            "Please enter the quantity.");
    return;
}

try {

    int quantity = Integer.parseInt(quantityText);

    if (quantity <= 0) {
        JOptionPane.showMessageDialog(this,
                "Quantity must be greater than 0.");
        return;
    }

    int medicineId = Integer.parseInt(
            selectedMedicine.split(" - ")[0]
    );

    Connection con = DatabaseConnection.getConnection();

    String sql = "SELECT name, price, quantity_in_stock "
               + "FROM medicines WHERE medicine_id = ?";

    PreparedStatement pst = con.prepareStatement(sql);
    pst.setInt(1, medicineId);

    ResultSet rs = pst.executeQuery();

    if (rs.next()) {

        String medicineName = rs.getString("name");
        double price = rs.getDouble("price");
        int stock = rs.getInt("quantity_in_stock");

        if (quantity > stock) {
            JOptionPane.showMessageDialog(this,
                    "Not enough stock available.\n"
                    + "Available stock: " + stock);

            rs.close();
            pst.close();
            con.close();
            return;
        }

        double subtotal = price * quantity;

        DefaultTableModel model =
                (DefaultTableModel) tblCartTwo.getModel();

        model.addRow(new Object[]{
            medicineId,
            medicineName,
            quantity,
            price,
            subtotal
        });

        total += subtotal;

        lblTotal.setText(
                String.format("Total: R%.2f", total)
        );

        txtQuantity.setText("");
    }

    rs.close();
    pst.close();
    con.close();

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "Please enter a valid number for quantity.",
            "Invalid Quantity",
            JOptionPane.ERROR_MESSAGE);

} catch (Exception e) {

    JOptionPane.showMessageDialog(this,
            "Database error: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        int row = tblCartTwo.getSelectedRow();

if (row < 0) {
    JOptionPane.showMessageDialog(this,
            "Please select an item in the cart first.");
    return;
}

DefaultTableModel model =
        (DefaultTableModel) tblCartTwo.getModel();

model.removeRow(row);

total = 0.0;

for (int i = 0; i < model.getRowCount(); i++) {

    double subtotal = Double.parseDouble(
            model.getValueAt(i, 4).toString()
    );

    total += subtotal;
}

lblTotal.setText(
        String.format("Total: R%.2f", total)
);
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCartActionPerformed
        DefaultTableModel model =
        (DefaultTableModel) tblCartTwo.getModel();

model.setRowCount(0);

total = 0.0;

lblTotal.setText("Total: R0.00");
    }//GEN-LAST:event_btnClearCartActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void showBill(int saleId) {

    DefaultTableModel model =
            (DefaultTableModel) tblCartTwo.getModel();

    StringBuilder bill = new StringBuilder();

    bill.append("========================================\n");
    bill.append("          HEALTHFIRST PHARMACY\n");
    bill.append("             SALES RECEIPT\n");
    bill.append("========================================\n");
    bill.append("Sale ID: ").append(saleId).append("\n");
    bill.append("Cashier: ").append(loggedInUserName).append("\n");
    bill.append("========================================\n");
    bill.append("Medicine              Qty       Amount\n");
    bill.append("----------------------------------------\n");

    for (int i = 0; i < model.getRowCount(); i++) {

        String medicine =
                model.getValueAt(i, 1).toString();

        int quantity =
                Integer.parseInt(model.getValueAt(i, 2).toString());

        double subtotal =
                Double.parseDouble(model.getValueAt(i, 4).toString());

        bill.append(String.format(
                "%-20s %3d     R%8.2f%n",
                medicine,
                quantity,
                subtotal
        ));
    }

    bill.append("----------------------------------------\n");
    bill.append(String.format(
            "TOTAL:                         R%.2f%n",
            total
    ));
    bill.append("========================================\n");
    bill.append("       Thank you for your purchase!\n");
    bill.append("========================================");

    JOptionPane.showMessageDialog(
            this,
            bill.toString(),
            "HealthFirst Pharmacy - Bill",
            JOptionPane.INFORMATION_MESSAGE
    );
}
    
    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
          if (tblCartTwo.getRowCount() == 0) {

        JOptionPane.showMessageDialog(this,
                "Cart is empty. Please add medicine first.");

        return;
    }

    Connection con = null;
    PreparedStatement salePst = null;
    PreparedStatement itemPst = null;
    PreparedStatement stockPst = null;
    ResultSet generatedKeys = null;

    try {

        con = DatabaseConnection.getConnection();

        // Start database transaction
        con.setAutoCommit(false);

        // 1. Create the sale
        String saleSql =
                "INSERT INTO sales (sale_date, total_amount, user_id) "
                + "VALUES (NOW(), ?, ?)";

        salePst = con.prepareStatement(
                saleSql,
                Statement.RETURN_GENERATED_KEYS
        );

        salePst.setDouble(1, total);
        salePst.setInt(2, loggedInUserId);

        salePst.executeUpdate();

        // Get the automatically generated sale_id
        generatedKeys = salePst.getGeneratedKeys();

        if (!generatedKeys.next()) {

            throw new Exception(
                    "Could not get the generated sale ID."
            );
        }

        int saleId = generatedKeys.getInt(1);

        // 2. Prepare sale item insert
        String itemSql =
                "INSERT INTO sale_items "
                + "(sale_id, medicine_id, quantity_sold, price_at_sale) "
                + "VALUES (?, ?, ?, ?)";

        itemPst = con.prepareStatement(itemSql);

        // 3. Prepare stock update
        String stockSql =
                "UPDATE medicines "
                + "SET quantity_in_stock = quantity_in_stock - ? "
                + "WHERE medicine_id = ? "
                + "AND quantity_in_stock >= ?";

        stockPst = con.prepareStatement(stockSql);

        DefaultTableModel model =
                (DefaultTableModel) tblCartTwo.getModel();

        // 4. Process every item in the cart
        for (int i = 0; i < model.getRowCount(); i++) {

            int medicineId = Integer.parseInt(
                    model.getValueAt(i, 0).toString()
            );

            int quantity = Integer.parseInt(
                    model.getValueAt(i, 2).toString()
            );

            double price = Double.parseDouble(
                    model.getValueAt(i, 3).toString()
            );

            // Insert sale item
            itemPst.setInt(1, saleId);
            itemPst.setInt(2, medicineId);
            itemPst.setInt(3, quantity);
            itemPst.setDouble(4, price);

            itemPst.executeUpdate();

            // Reduce stock
            stockPst.setInt(1, quantity);
            stockPst.setInt(2, medicineId);
            stockPst.setInt(3, quantity);

            int rowsUpdated = stockPst.executeUpdate();

            if (rowsUpdated != 1) {

                throw new Exception(
                        "Not enough stock available for medicine ID: "
                        + medicineId
                );
            }
        }

        // 5. Save everything
        con.commit();

        con.commit();
        
        //Show the full bill before clearing
        showBill(saleId);

        // 6. Clear the cart
        model.setRowCount(0);

        total = 0.0;

        lblTotal.setText("Total: R0.00");

        // 7. Refresh medicine list
        loadMedicines();

    } catch (Exception e) {

        try {

            if (con != null) {
                con.rollback();
            }

        } catch (Exception rollbackError) {

            JOptionPane.showMessageDialog(this,
                    "Rollback error: "
                    + rollbackError.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        JOptionPane.showMessageDialog(this,
                "Checkout failed: "
                + e.getMessage(),
                "Checkout Error",
                JOptionPane.ERROR_MESSAGE);

    } finally {

        try {
            if (generatedKeys != null) {
                generatedKeys.close();
            }

            if (salePst != null) {
                salePst.close();
            }

            if (itemPst != null) {
                itemPst.close();
            }

            if (stockPst != null) {
                stockPst.close();
            }

            if (con != null) {
                con.setAutoCommit(true);
                con.close();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Error closing database connection: "
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setOpaque(true);
        btnAdd.setContentAreaFilled(true);
        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setOpaque(false);
        btnAdd.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAddMouseExited

    private void btnRemoveItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveItemMouseEntered
        btnRemoveItem.setOpaque(true);
        btnRemoveItem.setContentAreaFilled(true);
        btnRemoveItem.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btnRemoveItemMouseEntered

    private void btnRemoveItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveItemMouseExited
        btnRemoveItem.setOpaque(false);
        btnRemoveItem.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRemoveItemMouseExited

    private void btnClearCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearCartMouseEntered
        btnClearCart.setOpaque(true);
        btnClearCart.setContentAreaFilled(true);
        btnClearCart.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btnClearCartMouseEntered

    private void btnClearCartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearCartMouseExited
        btnClearCart.setOpaque(false);
        btnClearCart.setContentAreaFilled(false);
    }//GEN-LAST:event_btnClearCartMouseExited

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered
        btnCheckout.setOpaque(true);
        btnCheckout.setContentAreaFilled(true);
        btnCheckout.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited
        btnCheckout.setOpaque(false);
        btnCheckout.setContentAreaFilled(false);
    }//GEN-LAST:event_btnCheckoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClearCart;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JComboBox<String> cmbMedicine;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCartTwo;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
