package healthfirstpims;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import healthfirstpims.database.DatabaseConnection;

public class ManageSuppliers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageSuppliers.class.getName());

    /**
     * Creates new form ManageSuppliers
     */
    public ManageSuppliers() {
        initComponents();
        loadSuppliers();
    }
    
    private void loadSuppliers() {
    String sql = "SELECT supplier_id, name, contact_person, phone, email, address "
               + "FROM suppliers ORDER BY supplier_id";

    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement pst = conn.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("supplier_id"),
                rs.getString("name"),
                rs.getString("contact_person"),
                rs.getString("phone"),
                rs.getString("email"),
                rs.getString("address")
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                this,
                "Error loading suppliers: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSupplierId = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        lblContactPerson = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtSupplierId = new javax.swing.JTextField();
        txtSupplierName = new javax.swing.JTextField();
        txtContactPerson = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnAddSupplier = new javax.swing.JButton();
        btnUpdateSupplier = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblSupplierList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("MANAGE SUPPLIERS");

        lblSupplierId.setText("Supplier ID:");

        lblSupplierName.setText("Supplier Name:");

        lblContactPerson.setText("Contact Person:");

        lblEmail.setText("Email:");

        lblAddress.setText("Address:");

        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.addActionListener(this::btnAddSupplierActionPerformed);

        btnUpdateSupplier.setText("Update Supplier");
        btnUpdateSupplier.addActionListener(this::btnUpdateSupplierActionPerformed);

        btnDeleteSupplier.setText("Delete Supplier");
        btnDeleteSupplier.addActionListener(this::btnDeleteSupplierActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        lblSupplierList.setText("Supplier List");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Supplier Name", "Contact Person", "Phone", "Email", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Phone:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSupplierId)
                                    .addComponent(lblSupplierName)
                                    .addComponent(lblContactPerson)
                                    .addComponent(lblEmail)
                                    .addComponent(lblAddress)
                                    .addComponent(jLabel1))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSupplierId)
                                    .addComponent(txtSupplierName)
                                    .addComponent(txtContactPerson)
                                    .addComponent(txtEmail)
                                    .addComponent(txtAddress)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRefresh)
                                        .addGap(108, 108, 108)
                                        .addComponent(lblSupplierList))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateSupplier)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierId)
                    .addComponent(txtSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierName)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContactPerson)
                    .addComponent(txtContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteSupplier)
                    .addComponent(btnUpdateSupplier)
                    .addComponent(btnAddSupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh))
                .addGap(11, 11, 11)
                .addComponent(lblSupplierList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        String name = txtSupplierName.getText().trim();
String contactPerson = txtContactPerson.getText().trim();
String phone = txtPhone.getText().trim();
String email = txtEmail.getText().trim();
String address = txtAddress.getText().trim();

if (name.isEmpty() || contactPerson.isEmpty() || phone.isEmpty()
        || email.isEmpty() || address.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Please fill in all supplier fields.",
            "Missing Information",
            JOptionPane.WARNING_MESSAGE
    );
    return;
}

String sql = "INSERT INTO suppliers "
           + "(name, contact_person, phone, email, address) "
           + "VALUES (?, ?, ?, ?, ?)";

try (Connection conn = DatabaseConnection.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql)) {

    pst.setString(1, name);
    pst.setString(2, contactPerson);
    pst.setString(3, phone);
    pst.setString(4, email);
    pst.setString(5, address);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(
            this,
            "Supplier added successfully."
    );

    loadSuppliers();

    txtSupplierId.setText("");
    txtSupplierName.setText("");
    txtContactPerson.setText("");
    txtPhone.setText("");
    txtEmail.setText("");
    txtAddress.setText("");

} catch (SQLException e) {
    JOptionPane.showMessageDialog(
            this,
            "Error adding supplier: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
    );
}
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();

    if (selectedRow >= 0) {
        txtSupplierId.setText(
                jTable1.getValueAt(selectedRow, 0).toString()
        );

        txtSupplierName.setText(
                jTable1.getValueAt(selectedRow, 1).toString()
        );

        txtContactPerson.setText(
                jTable1.getValueAt(selectedRow, 2).toString()
        );

        txtPhone.setText(
                jTable1.getValueAt(selectedRow, 3).toString()
        );

        txtEmail.setText(
                jTable1.getValueAt(selectedRow, 4).toString()
        );

        txtAddress.setText(
                jTable1.getValueAt(selectedRow, 5).toString()
        );
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupplierActionPerformed
        String supplierId = txtSupplierId.getText().trim();
String name = txtSupplierName.getText().trim();
String contactPerson = txtContactPerson.getText().trim();
String phone = txtPhone.getText().trim();
String email = txtEmail.getText().trim();
String address = txtAddress.getText().trim();

if (supplierId.isEmpty() || name.isEmpty() || contactPerson.isEmpty()
        || phone.isEmpty() || email.isEmpty() || address.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Please select a supplier and fill in all fields.",
            "Missing Information",
            JOptionPane.WARNING_MESSAGE
    );
    return;
}

String sql = "UPDATE suppliers SET name = ?, contact_person = ?, "
           + "phone = ?, email = ?, address = ? "
           + "WHERE supplier_id = ?";

try (Connection conn = DatabaseConnection.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql)) {

    pst.setString(1, name);
    pst.setString(2, contactPerson);
    pst.setString(3, phone);
    pst.setString(4, email);
    pst.setString(5, address);
    pst.setInt(6, Integer.parseInt(supplierId));

    int rowsUpdated = pst.executeUpdate();

    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(
                this,
                "Supplier updated successfully."
        );

        loadSuppliers();

        txtSupplierId.setText("");
        txtSupplierName.setText("");
        txtContactPerson.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtAddress.setText("");
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(
            this,
            "Error updating supplier: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
    );
}
    }//GEN-LAST:event_btnUpdateSupplierActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
      String supplierId = txtSupplierId.getText().trim();

    if (supplierId.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a supplier to delete.",
                "No Supplier Selected",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this supplier?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String sql = "DELETE FROM suppliers WHERE supplier_id = ?";

    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement pst = conn.prepareStatement(sql)) {

        pst.setInt(1, Integer.parseInt(supplierId));

        int rowsDeleted = pst.executeUpdate();

        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Supplier deleted successfully."
            );

            loadSuppliers();

            txtSupplierId.setText("");
            txtSupplierName.setText("");
            txtContactPerson.setText("");
            txtPhone.setText("");
            txtEmail.setText("");
            txtAddress.setText("");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                this,
                "Error deleting supplier: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadSuppliers();
        JOptionPane.showMessageDialog(this, "Supplier list refreshed successfully.");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageSuppliers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContactPerson;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSupplierId;
    private javax.swing.JLabel lblSupplierList;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactPerson;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
}
